export const PLAYER_CONTROL_URL = '/player';
export const PLAYER_HEARTBEAT_INTERVAL_MS = 20_000;
export const PLAYER_CONNECTION_TIMEOUT_MS = 60_000;
export const PLAYER_STATE_HEARTBEAT_TIMEOUT_MS = 45_000;
export const PLAYER_REPLACED_CLOSE_CODE = 4001;
export const PLAYER_STATE_TIMEOUT_CLOSE_CODE = 4002;
